apiVersion: apps/v1
kind: Deployment
metadata:
  name: rse-frontend
  namespace: rse-analytics
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rse-frontend
  template:
    metadata:
      labels:
        app: rse-frontend
    spec:
      containers:
        - name: frontend
          image: rse-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: rse-frontend
  namespace: rse-analytics
spec:
  selector:
    app: rse-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
