apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rse-ingress
  namespace: rse-analytics
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: rse.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rse-frontend
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: rse-backend
                port:
                  number: 5000
